- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Print env
      command: env
      register: x
      
    - name: x
      debug:
        msg: "{{ x }}"
