- name: Get Current JOB_ID
  hosts: all
  tasks:
    - name: Print env
      command: env
      register: x
      
    - name: x
      debug:
        msg: "{{ x }}"
        
    - name: Get JOB_ID from environment variables
      debug:
        msg: "{{ lookup('env','JOB_ID') }}"
