- name: Get Current JOB_ID
  hosts: all
  tasks:
        
    - name: Get JOB_ID from environment variables 1st option
      debug:
        msg: "{{ lookup('env','JOB_ID') }}"

    - name: Get JOB_ID from environment variables 2nd option
      debug:
        msg: "{{ ansible_env.JOB_ID }}"
        
    - name: Set_fact for current JOB_ID 
      set_fact:
        job_id: "{{ ansible_env.JOB_ID }}"
      
    - name: "[Tower] GetAccess Token"
      uri:
        url: "https://tower.ispworld.at//api/v1/authtoken/"
        validate_certs: true
        method: POST
        body: '{ "username": "admin", "password": "redhat" }'
        body_format: json
      register: result_token
    
    - debug: 
        msg: "{{result_token }}"
      
    - name: "[Tower] Get current job details"
      uri:
        url: "https://tower.ispworld.at/api/v2/jobs/{{ job_id }}"
        validate_certs: true
        method: GET
        force_basic_auth: true
        #user: "admin"
        #password: "redhat"
        status_code: 200
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer x"
        return_content: yes
      register: result_current_job

    - debug:
        msg: "{{ result_current_job.json.related.source_workflow_job }}"
